# Generated by Django 6.0 on 2026-01-06 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tours', '0005_alter_tableaddress_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TableUser',
        ),
    ]
