# Generated by Django 6.0 on 2026-01-02 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('navigator', '0007_alter_tabletravelpackages_display_price'),
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableTourPurchased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headcount', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0, null=True)),
                ('order_id', models.CharField(max_length=100, null=True)),
                ('payment_id', models.CharField(max_length=100, null=True)),
                ('order_status', models.CharField(max_length=20, null=True)),
                ('payment_method', models.CharField(max_length=100, null=True)),
                ('payment_status', models.CharField(max_length=20, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tableaddress')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navigator.tabletravelpackages')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tableuser')),
            ],
        ),
    ]
