# Generated by Django 6.0 on 2026-01-04 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tours', '0002_tabletourpurchased'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tableaddress',
            old_name='firstname',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='tableaddress',
            old_name='lastname',
            new_name='district',
        ),
        migrations.AddField(
            model_name='tableaddress',
            name='fullname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tableaddress',
            name='postcode',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tableaddress',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tableaddress',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.tableuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tabletourpurchased',
            name='checkin_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tabletourpurchased',
            name='checkin_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='tabletourpurchased',
            name='display_price',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabletourpurchased',
            name='invoice_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tabletourpurchased',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tabletourpurchased',
            name='room_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tabletourpurchased',
            name='vibe',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
