# Generated by Django 6.0 on 2026-01-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_rename_firstname_tableaddress_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabletourpurchased',
            name='energy_level',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tabletourpurchased',
            name='headcount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
