# Generated by Django 6.0 on 2026-01-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_alter_tableaddress_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabletourpurchased',
            name='duration',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
