# Generated by Django 6.0 on 2026-01-06 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_tabletourpurchased_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabletourpurchased',
            name='duration',
        ),
    ]
