# Generated by Django 6.0 on 2025-12-16 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableSubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='sub_categories/')),
                ('status', models.CharField(max_length=100, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='navigator.tablecategories')),
            ],
        ),
    ]
