# Generated by Django 6.0 on 2025-12-17 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0002_tablesubcategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='products/')),
                ('description', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('more', models.CharField(max_length=100, null=True)),
                ('sub_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='navigator.tablesubcategories')),
            ],
        ),
    ]
