# Generated by Django 6.0 on 2025-12-20 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0003_tableproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableTravelPackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('destination', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('duration', models.CharField(max_length=100, null=True)),
                ('price', models.FloatField(max_length=100, null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TableTravelPackagesMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(null=True, upload_to='travel_packages/')),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='navigator.tabletravelpackages')),
            ],
        ),
    ]
