# Generated by Django 6.0 on 2025-12-21 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0004_tabletravelpackages_tabletravelpackagesmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabletravelpackagesmedia',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='navigator.tabletravelpackages'),
        ),
    ]
