# Generated by Django 6.0 on 2026-01-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0005_alter_tabletravelpackagesmedia_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabletravelpackages',
            name='display_price',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
