# Generated by Django 6.0 on 2026-01-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0006_tabletravelpackages_display_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabletravelpackages',
            name='display_price',
            field=models.FloatField(max_length=100, null=True),
        ),
    ]
