# Generated by Django 6.0 on 2026-01-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0007_alter_tabletravelpackages_display_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabletravelpackages',
            name='price_for',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
