# Generated by Django 6.0 on 2026-01-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0008_tabletravelpackages_price_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabletravelpackages',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tabletravelpackages',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
