# Generated by Django 6.0 on 2026-01-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0009_tabletravelpackages_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabletravelpackages',
            name='tagline',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
