# Generated by Django 6.0 on 2026-01-27 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0010_tabletravelpackages_tagline'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=100, null=True)),
                ('content', models.TextField(null=True)),
                ('image1', models.ImageField(null=True, upload_to='blog/')),
                ('sub_content', models.TextField(null=True)),
                ('title2', models.CharField(max_length=100, null=True)),
                ('content2', models.TextField(null=True)),
                ('image2', models.ImageField(null=True, upload_to='blog/')),
                ('sub_content2', models.TextField(null=True)),
                ('summary_title', models.CharField(max_length=100, null=True)),
                ('summary_content', models.TextField(null=True)),
                ('tag', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('sub_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='navigator.tablesubcategories')),
            ],
        ),
        migrations.DeleteModel(
            name='TableProducts',
        ),
    ]
