# Generated by Django 6.0 on 2026-01-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0011_tableblog_delete_tableproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableblog',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
