# Generated by Django 6.0 on 2026-01-29 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0012_tableblog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablesubcategories',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='navigator.tablecategories'),
        ),
    ]
